# schema: https://raw.githubusercontent.com/iterative/dvcyaml-schema/master/schema.json

stages:
  prepare_data:
    cmd: uv run split_cicids2017.py
    deps:
      - data/CICIDS2017_improved
      - split_cicids2017.py
    outs:
      - data/train.csv
      - data/test.csv
  
  create_session_files:
    cmd: uv run create_session_files.py
    deps:
      - data/train.csv
      - create_session_files.py
    params:
      - create_sessions
    outs:
      - data/index_list/CICIDS2017_improved
      - data/class_distribution.txt
      - data/column_names.txt
  
  train_base:
    cmd: uv run train_base_session.py
    deps:
      - data/train.csv
      - data/test.csv
      - data/index_list/CICIDS2017_improved
      - train_base_session.py
    params:
      - train
    outs:
      - checkpoint/CICIDS2017_improved/session0_max_acc.pth
      - checkpoint/CICIDS2017_improved/session0confusion_matrix.png
      - checkpoint/CICIDS2017_improved/session0confusion_matrix_classification_report.txt
  
  train_new:
    foreach:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    do:
      cmd: uv run train_new_sessions.py --select_sessions ${item}
      deps:
        - data/train.csv
        - data/test.csv
        - data/index_list/CICIDS2017_improved
        - train_new_sessions.py
      params:
        - train
        - create_sessions
      outs:
        - checkpoint/CICIDS2017_improved/session${item}_max_acc.pth
        - checkpoint/CICIDS2017_improved/session${item}confusion_matrix.png
        - checkpoint/CICIDS2017_improved/session${item}confusion_matrix_classification_report.txt
