alpha: 0.5
balance: 0.001
base_class: 10
base_mode: ft_cos
batch_size_base: 2048
batch_size_new: 0
comet_disabled: true
comet_project: null
comet_tags:
- orm
comet_workspace: null
create_sessions:
  base_class: 10
  base_labels:
  - BENIGN
  - DrDoS_NetBIOS
  - LDAP
  - DrDoS_SSDP
  - WebDDoS
  - Syn
  - UDP
  - UDPLag
  - UDP-lag
  - DrDoS_DNS
  base_use_class_index: false
  dataset_name: CSECICIDS2018_improved
  label_column: Label
  max_samples_per_label: 10000000
  num_classes: 19
  output_dir: data/index_list
  seed: 62
  shot: 5
  way: 5
dataroot: data/
dataset_name: CICDDoS2019
dataset_type: CICIDS2017_improved
debug: false
decay: 0.0005
encoder: mlp
epochs_base: 1
epochs_new: 100
eta: 0.1
gamma: 0.1
gpu: '0'
input_dir: /home/ishibashi02/dataset/project/sampled/n_1000000_s_42
label_column: Label
loss_iter: 0
lr_base: 0.005
lr_new: 0.1
milestones:
- 60
- 70
model_dir: null
momentum: 0.9
new_mode: avg_cos
normalize_method: moving_minmax
not_data_init: false
num_classes: 19
num_workers: 8
project: fact
schedule: Cosine
seed: 62
set_no_val: false
shot: 5
start_session: 0
step: 20
temperature: 32
test_batch_size: 1024
way: 5
