common:
  device: cuda
  gpu: 0
  seed: 1
create_sessions:
  base_class: 4
  num_classes: 10
  output_dir: data/index_list/CICIDS2017_improved
  random_state: 1
  shot: 8
  train_csv: data/train.csv
  way: 1
dataset_presets:
  cifar100:
    alpha: 0.5
    balance: 0.001
    batch_size_base: 256
    decay: 0.0005
    epochs_base: 600
    gamma: 0.1
    loss_iter: 0
    lr_base: 0.1
    lr_new: 0.1
    schedule: Cosine
    temperature: 16
  cub200:
    balance: 0.01
    batch_size_base: 256
    decay: 0.0005
    epochs_base: 1
    gamma: 0.25
    loss_iter: 0
    lr_base: 0.005
    lr_new: 0.1
    milestones:
    - 60
    - 70
    schedule: Milestone
    temperature: 16
  mini_imagenet:
    alpha: 0.5
    balance: 0.01
    decay: 0.0005
    epochs_base: 1000
    eta: 0.1
    gamma: 0.1
    loss_iter: 150
    lr_base: 0.1
    lr_new: 0.1
    schedule: Cosine
    temperature: 16
paths:
  checkpoint_dir: checkpoint
  cicids_dir: data/CICIDS2017_improved
  cicids_index_dir: data/index_list/CICIDS2017_improved
  cub_dataroot: data/cub200
  data_dir: data
  mini_imagenet_root: data/mini_imagenet
  project_root: .
split_cicids:
  data_dir: data/CICIDS2017_improved
  output_dir: data/CICIDS2017_improved
  random_state: 1
  stratify: true
  test_size: 0.2
train:
  base:
    alpha: 2.0
    balance: 0.01
    base_mode: ft_cos
    batch_size_base: 128
    decay: 0.0005
    epochs_base: 10
    eta: 0.1
    gamma: 0.25
    loss_iter: 0
    lr_base: 0.005
    milestones:
    - 60
    - 70
    momentum: 0.9
    schedule: Cosine
    step: 20
    temperature: 1024
  common:
    dataroot: data
    dataset: CICIDS2017_improved
    debug: false
    encoder: cnn1d
    model_dir: null
    normalize_method: moving_minmax
    not_data_init: false
    num_workers: 8
    project: fact
    select_sessions: []
    set_no_val: false
    start_session: 0
    test_batch_size: 100
    wandb:
      entity: ''
      group: ''
      mode: online
      project: origin-fact
      run_name: ''
      tags: []
      use_wandb: false
      watch: gradients
      watch_freq: 100
  new:
    batch_size_new: 0
    epochs_new: 100
    lr_new: 0.1
    new_mode: avg_cos
