[project]
name = "fact"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "dvc[ssh]>=3.67.1",
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "optuna>=5.0.0",
    "pandas>=2.0.0",
    "pyarrow>=15.0.0",
    "pyyaml>=6.0",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.1",
    "wandb>=0.30.0",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cu126" }]
torchvision = [{ index = "pytorch-cu126" }]
pytorch-triton = [{ index = "pytorch-cu126" }]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]
